Repository kiegroup/droolsjbpm-build-bootstrap, pull requests merged in 2022-03, with the labels that each got.

#1897 forced PIM to build with jdk11
  .ci/daily-config.yaml
  .ci/jenkins/Jenkinsfile.daily
Labels: rebase-needed

#1899 Upgrade of mysql client to 8.0.27
  pom.xml
Labels: dependencies

#1918 DROOLS-6879 : Update to Wildfly core 17.x
  pom.xml
Labels: do_not_merge
